### ISSUE TITLE
Admin panel: Show "no applications yet" when nothing to fetch

### ISSUE THREAD

**Issue by cherrybeans** [webkom/committee-admissions#102]

**Comment by SmithPeder** [comment]
@kotlarz and I are looking into this. 

The description is quite short (read "non-existent")? Is this issue applying to the admin view "when viewing as a normal Committee leader"

**Comment by kotlarz** [comment]
The view displays 0 applications when there are no applications, we think this is good enough.

![image](https://user-images.githubusercontent.com/14221489/63651054-83431200-c751-11e9-9d3d-38f87766d9ee.png)
