### ISSUE TITLE
application/mine/ returns 404 if no registered application

### ISSUE THREAD

**Issue by cherrybeans** [webkom/committee-admissions#178]
The problem being that the endpoint is called before you have an application as well, so it shows up as 404.

Consider changing response from backend (I think that's the best way).

**Comment by SmithPeder** [comment]
@kotlarz and I looked over this issue. 

When the user just entered the site the `application/mine` will return `404 NOT FOUND` with no details. 

When the user enters after submitting an application the endpoint returns no content.

We suggest (as you suggested) that we change the response from `404 NOT FOUND` to the more concrete `204 NO CONTENT`.  This will not change the flow, but it will be more clear that this is intended response when you have no application.
