### ISSUE TITLE
Admin panel applications design

### ISSUE THREAD

**Issue by SmithPeder** [webkom/committee-admissions#369]
The design of the applications overview area is sup-par at best.

![image](https://user-images.githubusercontent.com/23152018/130993237-41856d91-084c-453f-9391-e072650e29b3.png)

One application is massive, and everything takes SPACE to say it mildly. This needs a redesign. I know a lot of users also used the mobile view last year, so we should strive to make it a bit mobile fiendly. 
![image](https://user-images.githubusercontent.com/23152018/130993271-85819c44-0b79-4bb4-be47-d932f8832d15.png)

**Comment by juniwbjerde** [comment]
The giant delete button has been fixed (in commit #406), but all the other styling stuff still needs to be looked at

**Comment by SmithPeder** [comment]
Wow 😮
