### ISSUE TITLE
HTTP request timed out (callApi) 

### ISSUE THREAD

**Issue by cherrybeans** [webkom/committee-admissions#83]
Happens when fetching data on admin page (prob. admissions endpoint)

**Comment by odinuge** [comment]
:+1: 

Should probably increase the timeout quite a bit (`5sec` right now):
https://github.com/webkom/committee-admissions/blob/fbd0eba874c2be6383d74fa57b33dfbb2b058663/frontend/src/utils/callApi.js#L57

**Comment by cherrybeans** [comment]
Fixed in c2132d5b50ac4a09aa4f2bb573cc80fcf70c6214
