### ISSUE TITLE
Add confidensiality note and note when data is deleted

### ISSUE THREAD

**Issue by cherrybeans** [webkom/committee-admissions#87]
- Committee leaders can only see the application to their committee, not your applications to other
 (but Abakus leader can see all) 
- All applications and data are deleted [insert time] after the admission is over

@edvardvb Do you have any input on what kind note we should display?

**Comment by edvardvb** [comment]
Not sure what you're asking for here? Is this a popup or text on the page explaining the confidentiality of the information?

It could be nice to inform the committee leader that they only see their own applications, but they should already know this. It could also be possible to inform them that the information is confidential within their committee. No one outside webkom should know who applied for webkom.

Informing them of the data deletion is also nice.

**Comment by cherrybeans** [comment]
Right, badly explained. We were thinking of adding a note to the user when applying of who can see their application and how long the data is stored. So maybe a card with text either at top of the application page, or near the submit butto.

**Comment by edvardvb** [comment]
Ah, I see. I haven't seen the current design, but a text shown before applying would be nice. "Din søknad til hver komité kan kun ses av den aktuelle komiteens leder, og leder av Abakus. All søknadsinformasjon slettes etter opptaket er gjennomført"
