### ISSUE TITLE
Endless authentication loop when normal user tries to access admin panel

### ISSUE THREAD

**Issue by cherrybeans** [webkom/committee-admissions#98]
Related to the "redirect on all 403" thing we put in to make things work temporarily.

**Comment by odinuge** [comment]
After #96 is merged, it should return `401` when the user is unauthorized (aka. has not logged in).  :smile:

**Comment by cherrybeans** [comment]
Fixed in 59b7a050f00d81cf02c3349c8ef3b98ae893654f
